# Generated by Django 4.0.6 on 2022-08-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_usename_likepost_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_like',
            new_name='no_of_likes',
        ),
    ]
